version: '2'
services:

    gn:
        build: ./live_gn
        expose:
            - "8009"
        links:
            - db
        volumes_from:
            - data
        container_name: "geonetwork"

    gs:
        build: ./live_gs
        expose:
            - "8009"
        links:
            - db
        volumes_from:
            - data
        container_name: "geoserver"

    db:
        build: ./live_db
        volumes_from:
            - data
    data:
        build: ./live_data
        ports:
            - "9102:9102"

    apache:
        build: 
            context: ./live_httpd
        ports:
            - "80:80"
            - "443:443"
        container_name: "apache"

